default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  database: rails_demo_march_2021_development

test:
  <<: *default
  username: postgres
  database: rails_demo_march_2021_test

production:
  <<: *default
  database: rails_demo_march_2021_production
  username: rails_demo_march_2021
  password: <%= ENV['RAILS_DEMO_MARCH_2021_DATABASE_PASSWORD'] %>
